config {
    type: "table",
    schema: "covid_data",
    name: "india_records",
    description: "get the india records from 1st January to 31st December",
}

SELECT
  date,
  country_code,
  country_name,
  subregion1_name,
  new_confirmed,
  new_deceased,
  new_recovered,
  cumulative_confirmed,
  cumulative_deceased,
  cumulative_recovered
FROM
  ${ref("filtered_covid")}
where
  country_name = 'India'
  AND date between "2022-01-01" AND "2022-12-31"
ORDER BY
  date DESC
LIMIT
  100